services:
  - type: web
    name: worldcup-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 src.app:app"
    region: oregon
    plan: free
    envVars:
      - key: postgresql://postgres:Glenwood%4027573@db.rzlwlqgtozuscpifzzre.supabase.co:5432/postgres?sslmode=require
        sync: false
